### ISSUE TITLE
Locality generators

### ISSUE THREAD

**Issue by camilstaps** [Dans-labs/text-fabric#2]
Perhaps I'm overlooking something but it seems there is on easy way to get the next *n* words using the locality API. You could chain `L.n`, but then you need to check continuously whether you have reached the last word or not. Would it be useful to add functionality to get a Python generator with `yield` that continues yielding next items until none are left?

I'm happy to implement it myself and create a PR, but wanted to check whether you think this is something useful to have in text-fabric and whether it would be better to extend the current `L.u` and `L.p` or create new methods.

**Comment by dirkroorda** [comment]
So you want to use `L.n(node, otype='word') repeatedly to get the next word.
If L.n were implemented to return a generator, you could then say

```python
for word in L.n(node, otype='word')():
    do something
```

But beware: theoretically `L.n(node, otype='subphrase')` might return multiple subphrases, all immediately following node. Because in the Bhsa subphrases lie embedded in each other.
When you chain multiple invocations of `L.n`, you pick the first result of it everytime, not the second one.

So the semantics of the auto-chained L.n is not as straightforward in general as it is for the `word` case.

Even less to for the L.u and L.d functions. For example, take L.u(word).
This results in a tuple like (subphrase, subphrase, phrase, clause, lex, sentence, verse, chapter, book).
Chaining means: pick the first result, a subphrase, and take the L.u of that, resulting in say
(phrase, clause, sentence, chapter book) where it is very well possible that the
second subphrase, the lex, and the verse fall out, because the first subphrase may contain multiple lexemes, so no single lex node contains it. The first and second subphrase might overlap but not be embedded in each other, so the second suphrase falls out. The first subphrase might span two verses, so no verse embeds it.

Because of this lack of clear semantics in the general case, I do not want to add chaining behaviour to the mechanism of text-fabric.
