### ISSUE TITLE
Option for Shuffled B.show Results

### ISSUE THREAD

**Issue by codykingham** [Dans-labs/text-fabric#24]
It would be nice to see `B.show` results in a randomized order. Though this is doable with an extra `random.shuffle` line, I find myself needing to do this quite often.

**Comment by codykingham** [comment]
e.g. `shuffle=True`

**Comment by dirkroorda** [comment]
Since this is such a simple thing to do, I am inclined to leave it out of the API, in order not to clutter it more. The specifics of the pretty display make `show()` into a pretty convoluted function already.

What you want is additional data manipulation. Search delivers an iterable of nodes, and before pushing them to `show()`, you can apply a whole battery of data transformations to those nodes.

So, when going this road, I think a need to write a function, call it `deliver()` that takes care of consuming the iterable, sorting, shuffling and condensing, in short, anything but presenting. 

An added bonus is that `deliver()` will be largely corpus independent, while `show()` is very corpus dependent.

Then I can unclutter `show()` a bit, by removing the condense parameters.

So I keep this in mind for when I find the time to address this.

**Comment by codykingham** [comment]
I agree that this is a very small piece of sugar. But also it can be really important for getting a sense of a grammatical phenomenon. Often a query will yield "clumps" of results in the Pentateuch, and unless the results are shuffled, you will only get a simplistic sense of the grammatical feature.

`deliver()` sounds nice. But would it still require an extra line of code? If so, then it is probably simpler just to continue using `random.shuffle`.

**Comment by dirkroorda** [comment]
Yes, by all means. Deliver would require an extra line of code. But you can make a utility lib for yourself, to reduce code in the notebook.

**Comment by codykingham** [comment]
Returning to this issue. `A.show` now seems to order the results, so that even when I shuffle my results myself, it has no effect. Either the sort function should be able to be toggled (probably preferable), or there should be shuffle option.

**Comment by dirkroorda** [comment]
It is not A.show() nor A.table() that do sorting, but A.search() does.
I have given A.search() an extra argument sort=... by which you can control the sorting behaviour.
`sort=True` is the default: results in canonical order
`sort=False` : no sorting at all
`sort=sortkey`: uses function sortkey to sort results.

**Comment by codykingham** [comment]
For some reason, my `A.show` is sorting a randomized list of results I'm feeding it.

**Comment by dirkroorda** [comment]
It is done, will be in the next release.

**Comment by dirkroorda** [comment]
Done
